### ISSUE TITLE
[BUG] Only extensions.json are synced (with GitBucket)

### ISSUE THREAD

**Issue by frankhommers** [arnohovhannisyan/vscode-syncify#20]
I know it's not supported, but I am using GitBucket. That partially works, only the extensions.json are uploaded.

I'd like gitbucket and gitea to be supported.

Great extension!

**Comment by arnohovhannisyan** [comment]
@frankhommers 

> I know it's not supported, but I am using GitBucket.

Technically, Syncify should work with any Git hosting service, so this is probably a problem with Syncify itself.

Can you install [this VSIX](https://cdn.discordapp.com/attachments/632780237637287966/641134943459606565/syncify-3.3.2.vsix) and start an upload? Then paste the console output where it says `Files to upload:`.

---

To open the console, go to `Help -> Toggle Developer Tools`

To install the VSIX, follow the instructions [here](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)

**Comment by frankhommers** [comment]
In the meantime I have switched to Gitea and that does seem to work! So forget about GitBucket for me ;-)

The plugin is great. Only the Settings UI is a bit unintuitive ;-)

**Comment by arnohovhannisyan** [comment]
@frankhommers 

> Only the Settings UI is a bit unintuitive

I'd love to know what is unintuitive about the Settings UI. Maybe we can discuss it on the Syncify Discord server since it doesn't have to do with this specific issue.

**Comment by allenyllee** [comment]
I have the same issue under Windows 10...

**Comment by arnohovhannisyan** [comment]
Reopening since this issue still exists (only on Windows).

**Comment by arnohovhannisyan** [comment]
@allenyllee Can you update the extension to the latest version, `v3.5.1`, and try uploading again?

**Comment by allenyllee** [comment]
@arnohovhannisyan I can upload settings on Windows now, but when I want to sync settings on ubuntu linux, it gives below error:

![Deepin 截圖_選取範圍_20191114115341](https://user-images.githubusercontent.com/3991134/68825557-72ad9280-06d5-11ea-933d-a431ef5810e6.png)

Maybe I should open another issue?

**Comment by arnohovhannisyan** [comment]
@allenyllee 

> Maybe I should open another issue?

Yes, please do that. We can discuss it over there.

**Comment by frankhommers** [comment]
What I would change in the settings UI is hide File Syncer options when you choose Repo and hide Repo Syncer options when you choose file.
