### ISSUE TITLE
[FEATURE] Support for internal Bitbucket Server?

### ISSUE THREAD

**Issue by dxman** [arnohovhannisyan/vscode-syncify#29]
### Is your feature request related to a problem?

Not a technical issue, just a nice-to-have feature.

### Describe the solution you'd like

The ability to provide the URL of a private Bitbucket Server instance (probably on the "getting started" window), in order to set up the required Application Permissions on my account.

### Describe alternatives you've considered

I'm currently syncing my settings to a repo on my personal GitHub account, and I can provide that URL to my coworkers as necessary.

### Additional context

I work on a team that uses an internal Bitbucket Server. In addition to syncing my own personal settings, I intend to create a minimal "beginner" profile that I can share with other members of my team, most of whom are new to VS Code. I can't guarantee that these individuals already have accounts on the public GitHub/GitLab/Bitbucket sites, but I know for certain that they have credentials for our internal server. This feature would mean one less step for them to follow.

Thanks very much for your hard work so far!

**Comment by arnohovhannisyan** [comment]
@dxman I have added this in `v3.9.0`.

## How to Use

1. Run `Syncify: Download`
2. Click the `Download without Login` button
3. Enter the URL of the "beginner" repository

This will download the beginner template, then remove the URL from the settings to prevent accidental uploads to the repo.

> If the repository on the BitBucket server is only readable when authenticated, they can use SSH or a personal access token.
>
> SSH Example: `git@your.endpoint.com:user/repo.git`
> PAT Example: `https://x-token-auth:token@your.endpoint.com/user/repo.git`
