### ISSUE TITLE
[BUG] Windows host, can't see error screen or debug logs

### ISSUE THREAD

**Issue by sharksforarms** [arnohovhannisyan/vscode-syncify#33]
### Syncify Version

I am using Syncify `v3.12.3`

### Describe the bug

Cannot upload to bitbucket, cannot see error on error screen (also tried enabling debug mode, don't see anything in console

### To Reproduce

Sign into bitbucket, add repo, upload

### Screenshots

![image](https://user-images.githubusercontent.com/10912917/72689255-9928e900-3add-11ea-917d-ad55df7cfa44.png)

### Additional context

Worked on linux host, tried to use on windows host, any other way to get debug logs?

**Comment by sharksforarms** [comment]
After digging into the webview source using dev tools I see this:

```
"Error: spawn git ENOENT\n\tat Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)\n\tat onErrorNT (internal/child_process.js:456:16)\n\tat processTicksAndRejections (internal/process/task_queues.js:84:9)"
```

Will investigate further

**Comment by arnohovhannisyan** [comment]
@sharksforarms Do you have `git` installed on your machine? If not, please follow the instructions [here][1].

[1]: https://arnohovhannisyan.space/vscode-syncify/docs/getting-started/prerequisites/#repo-syncer

**Comment by sharksforarms** [comment]
Re-installed git and got it working.
