### ISSUE TITLE
[FEATURE] Display error messages in pop up messages instead of tabs

### ISSUE THREAD

**Issue by nawordar** [arnohovhannisyan/vscode-syncify#34]
### Is your feature request related to a problem?
Error messages opening in new tabs are very obtrusive.

### Describe the solution you'd like
I suggest to replace them with pop up messages like on this [example](https://code.visualstudio.com/api/get-started/your-first-extension). For detailed description of a problem, the pop up could have a button labeled e.g. "Show details" that would open the same tab with description like it is done now.

**Comment by arnohovhannisyan** [comment]
@all-contributors please add @nawordar for ideas

**Comment by arnohovhannisyan** [comment]
@nawordar this has been implemented in `v3.13.2`.
