### ISSUE TITLE
Unable to Download from Syncify Repo

### ISSUE THREAD

**Issue by tbuico** [arnohovhannisyan/vscode-syncify#52]
### Syncify Version and Operating System

I am using Syncify `v4.0.4` on Linux inside of vscodium `1.47.0`on both computers.

### Describe the bug

Unable to Download from Syncify Github Repo

### To Reproduce
1. Setup Syncify on computer *A*
2. Init a new public Syncify repo in github using oauth
3. On computer *A*, run `Syncify: Upload`
4. Verify that the settings uploaded in to the new repo in github
5. Setup Syncify on computer *B* with github oauth
6. Chose the existing public Syncify repo in github in vscode
7. On computer *B*, run `Syncify: Download`
8. Receive error with the following message:
    ```
    Cannot read property 'length' of null
    ```
9. Restart vscodium
10. Discover that vscodium is corrupted and requires `rm -rf ~/.config/VSCodium` before it will use the extension marketplace again.

### Expected behavior

Expected Syncify to download the repo that computer *A* just uploaded to.

### Screenshots

![Screenshot_2020-07-13_17-59-38](https://user-images.githubusercontent.com/60446028/87369004-3e27fa00-c534-11ea-9419-d80ab36aaf14.png)

**Comment by arnohovhannisyan** [comment]
This is an issue with VSCode trying to use the same file Syncify uses for storing the current extensions, except that the formats are different so this error occurs. As a temporary workaround until the upstream PR is merged, run `rm -rf ~/.config/VSCodium/User/extensions.json` after downloading and reload the editor.

**Comment by arnohovhannisyan** [comment]
Actually, the workaround I just provided only works in VSCode. I'm currently working to see how to apply this on VSCodium.

**Comment by arnohovhannisyan** [comment]
Unfortunately this is an issue with VSCodium using OpenVSX as its extension marketplace (https://github.com/VSCodium/vscodium/issues/424). For a temporary solution, follow [this guide][1] to change your marketplace back to the Microsoft one.

[1]: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace
