### ISSUE TITLE
Error: No Stash Entries found. On a brand new installation.

### ISSUE THREAD

**Issue by kuddl** [arnohovhannisyan/vscode-syncify#58]
### Syncify Version and Operating System

I am using Syncify `v4.0.4` on Mac

### Describe the bug

I have 2 Macbooks.
Both use VSCodium (not VS Code).
On Mac1 I installed Syncify and startet uploading ... went OK.
On Mac2 I installed Syncify (no other extension; complete fresh VsCodium) -> Get Error "Keine Stash-Einträge gefunden" 

I tried:
* public vs. private repo
* reset vs. reinitiate
* complete uninistall 

The public repos is here:
https://github.com/kuddl/vsCodeSettings

**Comment by auxves** [comment]
This has been fixed in v4.0.5
